// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ORG.BasicInfo.Data;

#nullable disable

namespace ORG.BasicInfo.Data.Migrations
{
    [DbContext(typeof(FormsInfoDbContext))]
    partial class FormsInfoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ORG.BasicInfo.Domain.FormAggregate.FilesRawSys", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("FileSize")
                        .HasColumnType("decimal(20,0)");

                    b.Property<Guid>("IdFormRaw")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KeyFile")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("LUserCreate")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("UploadDate")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("IdFormRaw");

                    b.HasIndex("LUserCreate");

                    b.HasIndex("UploadDate");

                    b.ToTable("FilesRawSyss");
                });

            modelBuilder.Entity("ORG.BasicInfo.Domain.FormAggregate.FormRawLogSys", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("IdForm")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("FormRawLogSyss");
                });

            modelBuilder.Entity("ORG.BasicInfo.Domain.FormAggregate.FormRawRelatedUserSys", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdForm")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("IdForm");

                    b.HasIndex("IdUser");

                    b.ToTable("FormRawRelatedUserSys");
                });

            modelBuilder.Entity("ORG.BasicInfo.Domain.FormAggregate.FormRawSys", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(600)");

                    b.Property<long>("ExpireDate")
                        .HasColumnType("bigint");

                    b.Property<decimal>("IdCode")
                        .HasColumnType("decimal(20,0)");

                    b.Property<bool>("IsPublicForm")
                        .HasColumnType("bit");

                    b.Property<Guid>("LUserCreate")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LUserEdit")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<long>("TCreate")
                        .HasColumnType("bigint");

                    b.Property<long>("TEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ExpireDate");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("IdCode")
                        .IsUnique();

                    b.HasIndex("TCreate");

                    b.HasIndex("TEdit");

                    b.HasIndex("Title");

                    b.ToTable("FormRawSyss");
                });

            modelBuilder.Entity("ORG.BasicInfo.Domain.FormUserAggregate.FilesFormsSys", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("FileSize")
                        .HasColumnType("decimal(20,0)");

                    b.Property<Guid>("IdFormUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KeyFile")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<Guid>("LUserCreate")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(40)");

                    b.Property<long>("UploadDate")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("FilesFormsSyss");
                });

            modelBuilder.Entity("ORG.BasicInfo.Domain.FormUserAggregate.FormUserLogSys", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("IdFormRaw")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdFormUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUserRead")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StateAction")
                        .HasColumnType("int");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("FormUserLogSyss");
                });

            modelBuilder.Entity("ORG.BasicInfo.Domain.FormUserAggregate.FormUserSys", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("IdFormRaw")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUserRead")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LUserCreate")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LUserEdit")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("StateAction")
                        .HasColumnType("int");

                    b.Property<long>("TCreate")
                        .HasColumnType("bigint");

                    b.Property<long>("TEdit")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("FormUserSyss");
                });

            modelBuilder.Entity("ORG.BasicInfo.Domain.UserAggregate.PermissionFund", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdFund")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.ToTable("PermissionFunds");
                });

            modelBuilder.Entity("ORG.BasicInfo.Domain.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Certificate")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<decimal>("FundCode")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("FundName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("IdCodeNationalFund")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("IpUser")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("IsOrgUser")
                        .HasColumnType("bit");

                    b.Property<Guid>("LUserCreate")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LUserEdit")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("Mobile")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("NationalCodeUser")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<long>("TCreate")
                        .HasColumnType("bigint");

                    b.Property<long>("TEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("FundCode")
                        .IsUnique();

                    b.HasIndex("Mobile")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ORG.BasicInfo.Domain.FormAggregate.FilesRawSys", b =>
                {
                    b.HasOne("ORG.BasicInfo.Domain.FormAggregate.FormRawSys", null)
                        .WithMany("FilesRawOrgSys")
                        .HasForeignKey("IdFormRaw")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ORG.BasicInfo.Domain.FormAggregate.FormRawRelatedUserSys", b =>
                {
                    b.HasOne("ORG.BasicInfo.Domain.FormAggregate.FormRawSys", null)
                        .WithMany("UserFund")
                        .HasForeignKey("IdForm")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ORG.BasicInfo.Domain.UserAggregate.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ORG.BasicInfo.Domain.FormAggregate.FormRawSys", b =>
                {
                    b.Navigation("FilesRawOrgSys");

                    b.Navigation("UserFund");
                });
#pragma warning restore 612, 618
        }
    }
}
